// flow-typed signature: b3d5893e6624501b22b35b1e1a7c3367
// flow-typed version: <<STUB>>/dexie_v^1.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dexie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dexie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dexie/dist/dexie.es6' {
  declare module.exports: any;
}

declare module 'dexie/dist/dexie' {
  declare module.exports: any;
}

declare module 'dexie/dist/dexie.min' {
  declare module.exports: any;
}

declare module 'dexie/src/chaining-functions' {
  declare module.exports: any;
}

declare module 'dexie/src/debug' {
  declare module.exports: any;
}

declare module 'dexie/src/Dexie' {
  declare module.exports: any;
}

declare module 'dexie/src/errors' {
  declare module.exports: any;
}

declare module 'dexie/src/Events' {
  declare module.exports: any;
}

declare module 'dexie/src/promise-utils' {
  declare module.exports: any;
}

declare module 'dexie/src/Promise' {
  declare module.exports: any;
}

declare module 'dexie/src/utils' {
  declare module.exports: any;
}

declare module 'dexie/test/babel-polyfill/polyfill.min' {
  declare module.exports: any;
}

declare module 'dexie/test/dexie-unittest-utils' {
  declare module.exports: any;
}

declare module 'dexie/test/karma-env' {
  declare module.exports: any;
}

declare module 'dexie/test/karma.conf' {
  declare module.exports: any;
}

declare module 'dexie/test/karma.release.conf' {
  declare module.exports: any;
}

declare module 'dexie/test/karma.travis.conf' {
  declare module.exports: any;
}

declare module 'dexie/test/qunit' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-all' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-collection' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-crud-hooks' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-exception-handling' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-extendability' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-misc' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-open' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-performance' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-promise' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-table' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-transaction' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-upgrading' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-whereclause' {
  declare module.exports: any;
}

declare module 'dexie/test/tests-yield' {
  declare module.exports: any;
}

declare module 'dexie/test/worker' {
  declare module.exports: any;
}

declare module 'dexie/tools/build-utils' {
  declare module.exports: any;
}

declare module 'dexie/tools/build' {
  declare module.exports: any;
}

declare module 'dexie/tools/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dexie/dist/dexie.es6.js' {
  declare module.exports: $Exports<'dexie/dist/dexie.es6'>;
}
declare module 'dexie/dist/dexie.js' {
  declare module.exports: $Exports<'dexie/dist/dexie'>;
}
declare module 'dexie/dist/dexie.min.js' {
  declare module.exports: $Exports<'dexie/dist/dexie.min'>;
}
declare module 'dexie/src/chaining-functions.js' {
  declare module.exports: $Exports<'dexie/src/chaining-functions'>;
}
declare module 'dexie/src/debug.js' {
  declare module.exports: $Exports<'dexie/src/debug'>;
}
declare module 'dexie/src/Dexie.js' {
  declare module.exports: $Exports<'dexie/src/Dexie'>;
}
declare module 'dexie/src/errors.js' {
  declare module.exports: $Exports<'dexie/src/errors'>;
}
declare module 'dexie/src/Events.js' {
  declare module.exports: $Exports<'dexie/src/Events'>;
}
declare module 'dexie/src/promise-utils.js' {
  declare module.exports: $Exports<'dexie/src/promise-utils'>;
}
declare module 'dexie/src/Promise.js' {
  declare module.exports: $Exports<'dexie/src/Promise'>;
}
declare module 'dexie/src/utils.js' {
  declare module.exports: $Exports<'dexie/src/utils'>;
}
declare module 'dexie/test/babel-polyfill/polyfill.min.js' {
  declare module.exports: $Exports<'dexie/test/babel-polyfill/polyfill.min'>;
}
declare module 'dexie/test/dexie-unittest-utils.js' {
  declare module.exports: $Exports<'dexie/test/dexie-unittest-utils'>;
}
declare module 'dexie/test/karma-env.js' {
  declare module.exports: $Exports<'dexie/test/karma-env'>;
}
declare module 'dexie/test/karma.conf.js' {
  declare module.exports: $Exports<'dexie/test/karma.conf'>;
}
declare module 'dexie/test/karma.release.conf.js' {
  declare module.exports: $Exports<'dexie/test/karma.release.conf'>;
}
declare module 'dexie/test/karma.travis.conf.js' {
  declare module.exports: $Exports<'dexie/test/karma.travis.conf'>;
}
declare module 'dexie/test/qunit.js' {
  declare module.exports: $Exports<'dexie/test/qunit'>;
}
declare module 'dexie/test/tests-all.js' {
  declare module.exports: $Exports<'dexie/test/tests-all'>;
}
declare module 'dexie/test/tests-collection.js' {
  declare module.exports: $Exports<'dexie/test/tests-collection'>;
}
declare module 'dexie/test/tests-crud-hooks.js' {
  declare module.exports: $Exports<'dexie/test/tests-crud-hooks'>;
}
declare module 'dexie/test/tests-exception-handling.js' {
  declare module.exports: $Exports<'dexie/test/tests-exception-handling'>;
}
declare module 'dexie/test/tests-extendability.js' {
  declare module.exports: $Exports<'dexie/test/tests-extendability'>;
}
declare module 'dexie/test/tests-misc.js' {
  declare module.exports: $Exports<'dexie/test/tests-misc'>;
}
declare module 'dexie/test/tests-open.js' {
  declare module.exports: $Exports<'dexie/test/tests-open'>;
}
declare module 'dexie/test/tests-performance.js' {
  declare module.exports: $Exports<'dexie/test/tests-performance'>;
}
declare module 'dexie/test/tests-promise.js' {
  declare module.exports: $Exports<'dexie/test/tests-promise'>;
}
declare module 'dexie/test/tests-table.js' {
  declare module.exports: $Exports<'dexie/test/tests-table'>;
}
declare module 'dexie/test/tests-transaction.js' {
  declare module.exports: $Exports<'dexie/test/tests-transaction'>;
}
declare module 'dexie/test/tests-upgrading.js' {
  declare module.exports: $Exports<'dexie/test/tests-upgrading'>;
}
declare module 'dexie/test/tests-whereclause.js' {
  declare module.exports: $Exports<'dexie/test/tests-whereclause'>;
}
declare module 'dexie/test/tests-yield.js' {
  declare module.exports: $Exports<'dexie/test/tests-yield'>;
}
declare module 'dexie/test/worker.js' {
  declare module.exports: $Exports<'dexie/test/worker'>;
}
declare module 'dexie/tools/build-utils.js' {
  declare module.exports: $Exports<'dexie/tools/build-utils'>;
}
declare module 'dexie/tools/build.js' {
  declare module.exports: $Exports<'dexie/tools/build'>;
}
declare module 'dexie/tools/watch.js' {
  declare module.exports: $Exports<'dexie/tools/watch'>;
}
