// flow-typed signature: 22717e3d91282fca79a59c747bde9276
// flow-typed version: <<STUB>>/react-titlebar-osx_v^1.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-titlebar-osx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-titlebar-osx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-titlebar-osx/demo/demo-bundle' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/demo/js/basicDemo' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/demo/js/index' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/lib/Titlebar' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/umd/ReactTitlebar' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/umd/ReactTitlebar.min' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/webpack-demo.config' {
  declare module.exports: any;
}

declare module 'react-titlebar-osx/webpack-umd.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-titlebar-osx/demo/demo-bundle.js' {
  declare module.exports: $Exports<'react-titlebar-osx/demo/demo-bundle'>;
}
declare module 'react-titlebar-osx/demo/js/basicDemo.js' {
  declare module.exports: $Exports<'react-titlebar-osx/demo/js/basicDemo'>;
}
declare module 'react-titlebar-osx/demo/js/index.js' {
  declare module.exports: $Exports<'react-titlebar-osx/demo/js/index'>;
}
declare module 'react-titlebar-osx/index' {
  declare module.exports: $Exports<'react-titlebar-osx'>;
}
declare module 'react-titlebar-osx/index.js' {
  declare module.exports: $Exports<'react-titlebar-osx'>;
}
declare module 'react-titlebar-osx/lib/Titlebar.js' {
  declare module.exports: $Exports<'react-titlebar-osx/lib/Titlebar'>;
}
declare module 'react-titlebar-osx/umd/ReactTitlebar.js' {
  declare module.exports: $Exports<'react-titlebar-osx/umd/ReactTitlebar'>;
}
declare module 'react-titlebar-osx/umd/ReactTitlebar.min.js' {
  declare module.exports: $Exports<'react-titlebar-osx/umd/ReactTitlebar.min'>;
}
declare module 'react-titlebar-osx/webpack-demo.config.js' {
  declare module.exports: $Exports<'react-titlebar-osx/webpack-demo.config'>;
}
declare module 'react-titlebar-osx/webpack-umd.config.js' {
  declare module.exports: $Exports<'react-titlebar-osx/webpack-umd.config'>;
}
